import { useState, useEffect, useMemo } from 'react'

export interface GitHubAuthor {
  login: string
  avatarUrl: string
  url: string
}

export interface GitHubReactions {
  '+1': number
  '-1': number
  heart: number
  hooray: number
  laugh: number
  rocket: number
  eyes: number
  total: number
}

export interface GitHubIssue {
  id: number
  title: string
  body: string
  state: 'open' | 'closed'
  labels: string[]
  author: GitHubAuthor
  url: string
  comments: number
  reactions: GitHubReactions
  createdAt: string
  updatedAt: string
}

export interface GitHubLabel {
  name: string
  description: string
  color: string
}

interface GitHubIssuesData {
  lastUpdated: string
  repo: string
  repoUrl: string
  labels: GitHubLabel[]
  issues: GitHubIssue[]
}

export type SortMode = 'votes' | 'newest' | 'oldest' | 'recent-activity'

/**
 * Sections we display, mapped from GitHub labels.
 * Each section has an id (matching the label name), an icon hint, and sort defaults.
 */
export interface SectionConfig {
  labelName: string
  defaultSort: SortMode
  allowVoteSort: boolean
}

/**
 * The sections we create from GitHub labels.
 * 'duplicate' is excluded. Labels that "make sense" as community sections.
 */
export const SECTION_CONFIGS: SectionConfig[] = [
  { labelName: 'topic request', defaultSort: 'votes', allowVoteSort: true },
  { labelName: 'workshop proposal', defaultSort: 'votes', allowVoteSort: true },
  { labelName: 'ops enhancement', defaultSort: 'votes', allowVoteSort: true },
  { labelName: 'help wanted', defaultSort: 'recent-activity', allowVoteSort: false },
  { labelName: 'question', defaultSort: 'recent-activity', allowVoteSort: false },
]

/**
 * Get the total "upvote score" for an issue.
 * We count +1, heart, hooray, and rocket as positive signals.
 */
export function getUpvoteScore(issue: GitHubIssue): number {
  const r = issue.reactions
  return r['+1'] + r.heart + r.hooray + r.rocket
}

/**
 * Sort issues by the given mode.
 */
export function sortIssues(issues: GitHubIssue[], mode: SortMode): GitHubIssue[] {
  const sorted = [...issues]
  switch (mode) {
    case 'votes':
      return sorted.sort((a, b) => {
        const diff = getUpvoteScore(b) - getUpvoteScore(a)
        if (diff !== 0) return diff
        // Tie-break: more comments first
        return b.comments - a.comments
      })
    case 'newest':
      return sorted.sort(
        (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime()
      )
    case 'oldest':
      return sorted.sort(
        (a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime()
      )
    case 'recent-activity':
      return sorted.sort(
        (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
      )
    default:
      return sorted
  }
}

interface UseGitHubIssuesReturn {
  issues: GitHubIssue[]
  labels: GitHubLabel[]
  loading: boolean
  error: string | null
  repoUrl: string
  lastUpdated: string | null
  getIssuesByLabel: (labelName: string) => GitHubIssue[]
  getUnlabeledIssues: () => GitHubIssue[]
}

/**
 * Hook to load GitHub issues from the pre-fetched static JSON file.
 * The JSON is generated by scripts/fetch-github-issues.mjs and
 * kept up-to-date by a GitHub Actions cron workflow.
 */
export function useGitHubIssues(): UseGitHubIssuesReturn {
  const [data, setData] = useState<GitHubIssuesData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    async function load() {
      try {
        const res = await fetch(`/github-issues.json?t=${Date.now()}`)
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const json: GitHubIssuesData = await res.json()
        if (!cancelled) {
          setData(json)
          setLoading(false)
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load issues')
          setLoading(false)
        }
      }
    }

    load()
    return () => {
      cancelled = true
    }
  }, [])

  const getIssuesByLabel = useMemo(() => {
    if (!data) return (_label: string) => [] as GitHubIssue[]
    return (labelName: string) => data.issues.filter((i) => i.labels.includes(labelName))
  }, [data])

  const getUnlabeledIssues = useMemo(() => {
    if (!data) return () => [] as GitHubIssue[]
    return () => data.issues.filter((i) => i.labels.length === 0)
  }, [data])

  return {
    issues: data?.issues ?? [],
    labels: data?.labels ?? [],
    loading,
    error,
    repoUrl: data?.repoUrl ?? 'https://github.com/TorinoJS/discussion',
    lastUpdated: data?.lastUpdated ?? null,
    getIssuesByLabel,
    getUnlabeledIssues,
  }
}

/**
 * Format a relative time string (e.g., "3 days ago", "2 months ago").
 */
export function formatRelativeTime(isoString: string, locale: 'it' | 'en'): string {
  const date = new Date(isoString)
  const now = new Date()
  const diffMs = now.getTime() - date.getTime()
  const diffSec = Math.floor(diffMs / 1000)
  const diffMin = Math.floor(diffSec / 60)
  const diffHour = Math.floor(diffMin / 60)
  const diffDay = Math.floor(diffHour / 24)
  const diffMonth = Math.floor(diffDay / 30)
  const diffYear = Math.floor(diffDay / 365)

  if (locale === 'it') {
    if (diffYear > 0) return diffYear === 1 ? '1 anno fa' : `${diffYear} anni fa`
    if (diffMonth > 0) return diffMonth === 1 ? '1 mese fa' : `${diffMonth} mesi fa`
    if (diffDay > 0) return diffDay === 1 ? '1 giorno fa' : `${diffDay} giorni fa`
    if (diffHour > 0) return diffHour === 1 ? "1 ora fa" : `${diffHour} ore fa`
    if (diffMin > 0) return diffMin === 1 ? '1 minuto fa' : `${diffMin} minuti fa`
    return 'adesso'
  }

  if (diffYear > 0) return diffYear === 1 ? '1 year ago' : `${diffYear} years ago`
  if (diffMonth > 0) return diffMonth === 1 ? '1 month ago' : `${diffMonth} months ago`
  if (diffDay > 0) return diffDay === 1 ? '1 day ago' : `${diffDay} days ago`
  if (diffHour > 0) return diffHour === 1 ? '1 hour ago' : `${diffHour} hours ago`
  if (diffMin > 0) return diffMin === 1 ? '1 minute ago' : `${diffMin} minutes ago`
  return 'just now'
}

/**
 * Truncate a string to a maximum length, adding ellipsis if needed.
 */
export function truncateBody(body: string, maxLength = 200): string {
  if (!body) return ''
  // Strip markdown images and links for preview
  const clean = body
    .replace(/!\[[^\]]*\]\([^)]+\)/g, '') // remove images
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1') // replace links with text
    .replace(/[#*_~`>]/g, '') // strip markdown formatting
    .replace(/\n+/g, ' ') // collapse newlines
    .trim()
  if (clean.length <= maxLength) return clean
  return clean.slice(0, maxLength).trimEnd() + '...'
}
