import { useState, useEffect, useMemo } from 'react'

export interface MeetupEvent {
  id: string
  title: string
  description: string
  url: string
  start: string
  end: string | null
  location: string | null
  status: string
}

interface MeetupEventsData {
  lastUpdated: string
  source: string
  groupUrl: string
  events: MeetupEvent[]
}

interface UseMeetupEventsReturn {
  upcoming: MeetupEvent[]
  past: MeetupEvent[]
  nextEvent: MeetupEvent | null
  loading: boolean
  error: string | null
  groupUrl: string
  lastUpdated: string | null
}

/**
 * Hook to load Meetup events from the static JSON file.
 * The JSON is generated by scripts/fetch-meetup-events.mjs and
 * kept up-to-date by the GitHub Actions cron workflow.
 *
 * Events are split into upcoming/past based on the current time,
 * so even if the JSON was fetched hours ago, the display is always correct.
 */
export function useMeetupEvents(): UseMeetupEventsReturn {
  const [data, setData] = useState<MeetupEventsData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    let cancelled = false

    async function load() {
      try {
        // Cache-bust with a timestamp query param so browsers don't serve stale data
        const res = await fetch(`/meetup-events.json?t=${Date.now()}`)
        if (!res.ok) throw new Error(`HTTP ${res.status}`)
        const json: MeetupEventsData = await res.json()
        if (!cancelled) {
          setData(json)
          setLoading(false)
        }
      } catch (err) {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : 'Failed to load events')
          setLoading(false)
        }
      }
    }

    load()
    return () => { cancelled = true }
  }, [])

  const upcoming = useMemo(() => {
    if (!data) return []
    const now = new Date()
    return data.events
      .filter((e) => new Date(e.start) > now)
      .sort((a, b) => new Date(a.start).getTime() - new Date(b.start).getTime())
  }, [data])

  const past = useMemo(() => {
    if (!data) return []
    const now = new Date()
    return data.events
      .filter((e) => new Date(e.start) <= now)
      .sort((a, b) => new Date(b.start).getTime() - new Date(a.start).getTime())
  }, [data])

  return {
    upcoming,
    past,
    nextEvent: upcoming.length > 0 ? upcoming[0] : null,
    loading,
    error,
    groupUrl: data?.groupUrl ?? 'https://www.meetup.com/torino-js/',
    lastUpdated: data?.lastUpdated ?? null,
  }
}

/**
 * Format an ISO date string for display, respecting the user's locale.
 */
export function formatEventDate(isoString: string, locale: 'it' | 'en'): string {
  const date = new Date(isoString)
  return date.toLocaleDateString(locale === 'it' ? 'it-IT' : 'en-US', {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  })
}

/**
 * Format the time portion of an ISO date string.
 */
export function formatEventTime(isoString: string, locale: 'it' | 'en'): string {
  const date = new Date(isoString)
  return date.toLocaleTimeString(locale === 'it' ? 'it-IT' : 'en-US', {
    hour: '2-digit',
    minute: '2-digit',
  })
}

/**
 * Format a time range string like "19:00 - 21:00".
 */
export function formatEventTimeRange(
  start: string,
  end: string | null,
  locale: 'it' | 'en'
): string {
  const startTime = formatEventTime(start, locale)
  if (!end) return startTime
  const endTime = formatEventTime(end, locale)
  return `${startTime} - ${endTime}`
}

/**
 * Check if an event is happening today.
 */
export function isToday(isoString: string): boolean {
  const date = new Date(isoString)
  const now = new Date()
  return (
    date.getFullYear() === now.getFullYear() &&
    date.getMonth() === now.getMonth() &&
    date.getDate() === now.getDate()
  )
}

/**
 * Check if an event is happening tomorrow.
 */
export function isTomorrow(isoString: string): boolean {
  const date = new Date(isoString)
  const tomorrow = new Date()
  tomorrow.setDate(tomorrow.getDate() + 1)
  return (
    date.getFullYear() === tomorrow.getFullYear() &&
    date.getMonth() === tomorrow.getMonth() &&
    date.getDate() === tomorrow.getDate()
  )
}

/**
 * Extract month abbreviation and day number from an ISO date string.
 */
export function extractDateParts(
  isoString: string,
  locale: 'it' | 'en'
): { month: string; day: string } {
  const date = new Date(isoString)
  const month = date
    .toLocaleDateString(locale === 'it' ? 'it-IT' : 'en-US', { month: 'short' })
    .toUpperCase()
    .replace('.', '')
  const day = date.getDate().toString()
  return { month, day }
}
